services:
  cshort:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CSHORT_DATABASE: ${CSHORT_DATABASE}
      CSHORT_MIGRATIONS_PATH: db/migrations
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    image: postgres:17.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
