apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chaos-shortener.fullname" . }}
  labels:
    {{- include "chaos-shortener.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 10s
      targetPort: http
      path: /metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "chaos-shortener.selectorLabels" . | nindent 6 }}
